from django.db import models


class Roadmap(models.Model):
    """A complete career roadmap (e.g. Frontend Developer)"""
    slug = models.SlugField(unique=True)           # 'frontend-developer'
    title = models.CharField(max_length=200)        # 'Frontend Developer'
    description = models.TextField()
    icon = models.CharField(max_length=10, default='💻')  # emoji
    color = models.CharField(max_length=20, default='orange')  # tailwind color name
    category = models.CharField(max_length=100, default='Web Development')
    # RemoteOK job tags to match against
    job_tags = models.JSONField(default=list)       # ['react', 'javascript', 'frontend']
    estimated_months = models.IntegerField(default=6)
    is_trending = models.BooleanField(default=False)
    is_custom = models.BooleanField(default=False)  # True if generated by Gemini for a specific user
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-is_trending', 'title']

    def __str__(self):
        return self.title


class SkillNode(models.Model):
    """A skill/topic within a roadmap"""
    DIFFICULTY_CHOICES = [('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')]

    roadmap = models.ForeignKey(Roadmap, on_delete=models.CASCADE, related_name='nodes')
    title = models.CharField(max_length=200)
    description = models.TextField()
    resource_url = models.URLField(blank=True)      # Primary doc link (MDN)
    video_url = models.URLField(blank=True, null=True)      # YouTube free link
    paid_course_url = models.URLField(blank=True, null=True) # Recommended paid course
    project_description = models.TextField(blank=True)       # For the secure workspace
    difficulty = models.CharField(max_length=20, choices=DIFFICULTY_CHOICES, default='beginner')
    order = models.IntegerField(default=0)          # position in roadmap
    estimated_days = models.IntegerField(default=3)
    prerequisites = models.ManyToManyField('self', blank=True, symmetrical=False, related_name='unlocks')
    is_required = models.BooleanField(default=True)
    
    # New Phase 6 Fields
    assessment_type = models.CharField(max_length=20, default='coding') # 'coding' or 'mcq'
    assessment_data = models.JSONField(default=dict, blank=True) # Coding instructions or MCQ json

    class Meta:
        ordering = ['roadmap', 'order']

    def __str__(self):
        return f"{self.roadmap.title} → {self.title}"


class RoleAnalysis(models.Model):
    """Cached Gemini analysis for a role (refreshed periodically)"""
    role_slug = models.SlugField(unique=True)
    role_title = models.CharField(max_length=200)
    salary_range = models.CharField(max_length=100, blank=True)  # '₹8L – ₹25L / yr'
    demand_level = models.CharField(max_length=20, default='high')  # high/medium/low
    live_job_count = models.IntegerField(default=0)
    must_have_skills = models.JSONField(default=list)
    nice_to_have_skills = models.JSONField(default=list)
    interview_topics = models.JSONField(default=list)
    industry_description = models.TextField(blank=True)  # Gemini-generated
    roadmap = models.ForeignKey(Roadmap, on_delete=models.SET_NULL, null=True, blank=True, related_name='analysis')
    cached_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Analysis: {self.role_title}"


class Enrollment(models.Model):
    """User enrollment in a specific roadmap"""
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='role_enrollments')
    roadmap = models.ForeignKey(Roadmap, on_delete=models.CASCADE)
    current_tier = models.CharField(max_length=20, default='beginner') # beginner/intermediate/advanced
    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = ('user', 'roadmap')

    def __str__(self):
        return f"{self.user.username} enrolled in {self.roadmap.title}"


class UserNodeProgress(models.Model):
    """Tracks completion of specific nodes for a user"""
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='node_progress')
    node = models.ForeignKey(SkillNode, on_delete=models.CASCADE)
    is_completed = models.BooleanField(default=False)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = ('user', 'node')

    def __str__(self):
        return f"{self.user.username} | {self.node.title} | {self.is_completed}"
class GeneratedResume(models.Model):
    """Stores the path and metadata for a dynamically generated resume"""
    enrollment = models.OneToOneField(Enrollment, on_delete=models.CASCADE, related_name='generated_resume')
    pdf_path = models.CharField(max_length=500, blank=True)
    tier_at_generation = models.CharField(max_length=20) # beginner/intermediate/advanced
    last_generated_at = models.DateTimeField(auto_now=True)
    is_public = models.BooleanField(default=False)
    share_slug = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):
        return f"Resume: {self.enrollment.user.username} - {self.enrollment.roadmap.title} ({self.tier_at_generation})"


class ResumeProfile(models.Model):
    """User-provided professional details for the Resume Engine"""
    user = models.OneToOneField('users.User', on_delete=models.CASCADE, related_name='resume_profile')
    phone = models.CharField(max_length=20, blank=True)
    location = models.CharField(max_length=100, blank=True) # e.g. "San Francisco, CA"
    linkedin_url = models.URLField(blank=True)
    github_url = models.URLField(blank=True)
    portfolio_url = models.URLField(blank=True)
    professional_summary = models.TextField(blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Profile: {self.user.username}"
