# Generated by Django 5.1.4 on 2026-02-26 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='💻', max_length=10)),
                ('color', models.CharField(default='orange', max_length=20)),
                ('category', models.CharField(default='Web Development', max_length=100)),
                ('job_tags', models.JSONField(default=list)),
                ('estimated_months', models.IntegerField(default=6)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_trending', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_slug', models.SlugField(unique=True)),
                ('role_title', models.CharField(max_length=200)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('demand_level', models.CharField(default='high', max_length=20)),
                ('live_job_count', models.IntegerField(default=0)),
                ('must_have_skills', models.JSONField(default=list)),
                ('nice_to_have_skills', models.JSONField(default=list)),
                ('interview_topics', models.JSONField(default=list)),
                ('industry_description', models.TextField(blank=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis', to='roles.roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_url', models.URLField(blank=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('estimated_days', models.IntegerField(default=3)),
                ('is_required', models.BooleanField(default=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='roles.skillnode')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='roles.roadmap')),
            ],
            options={
                'ordering': ['roadmap', 'order'],
            },
        ),
    ]
