# Generated by Django 6.0.2 on 2026-02-26 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillnode',
            name='paid_course_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillnode',
            name='project_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skillnode',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tier', models.CharField(default='beginner', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.roadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'roadmap')},
            },
        ),
        migrations.CreateModel(
            name='UserNodeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.skillnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'node')},
            },
        ),
    ]
