# Generated by Django 5.1.4 on 2026-02-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_roadmap_is_custom_skillnode_paid_course_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillnode',
            name='assessment_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='skillnode',
            name='assessment_type',
            field=models.CharField(default='coding', max_length=20),
        ),
    ]
