# Generated by Django 5.1.4 on 2026-02-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_skillnode_assessment_data_skillnode_assessment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('tier_at_generation', models.CharField(max_length=20)),
                ('last_generated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('share_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_resume', to='roles.enrollment')),
            ],
        ),
    ]
